version: '3.7'
services:
  tempo:
    image: grafana/tempo:1.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    ports:
      - "14268" # jaeger ingest, Jaeger - Thrift HTTP
      - "14250" # Jaeger - GRPC
      - "55680" # OpenTelemetry
      - "6831/udp" # Jaeger - Thrift Compact
      - "6832/udp" # Jaeger - Thrift Binary
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/loki-local.yaml
    ports:
      - "3100:3100" # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./data/loki-data:/tmp/loki
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  volume_exporter:
    image: mnadeem/volume_exporter
    command:
      [
        "--volume-dir=tempo:/tmp/tempo",
        "--volume-dir=logs:/app/logs",
        "--volume-dir=loki:/tmp/loki"
      ]
    volumes:
      - ./data/logs:/app/logs
      - ./data/tempo-data:/tmp/tempo
      - ./data/loki-data:/tmp/loki
    ports:
      - 9889:9888
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - nestjs-example
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.1.1-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
      - volume_exporter
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  nestjs-example:
    build: .
    ports:
      - 5555:5555
      - 8081:8081
    volumes:
      - ./data/logs:/app/logs
    environment:
      OTEL_SERVICE_NAME: nestjs-full-example
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://tempo:14268/api/traces
      LOG_FILE_NAME: /app/logs/nestjs-example.log
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
